services:
  - type: web
    name: movie-explorer-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
